ferdelance:
  client:
    server: ${SERVER}
    heartbeat: 10.0
    workdir: ./workdir

  datasource:
    - name: california1
      type: csv
      path: "/ferdelance/data/california_housing.MedInc1.csv"
      kind: file
