version: '3.3'

networks:
  ferdelance:
  www:
    external: true

volumes:
  ferdelance-server-data:
  ferdelance-db-data:

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_SCHEMA}
    volumes:
      - ferdelance-db-data:/var/lib/postgresql/data
    networks:
      - ferdelance

  server: 
    image: idsia.ferdelance.server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}/${DATABASE_SCHEMA}
      - SERVER_MAIN_PASSWORD=${SERVER_MAIN_PASSWORD}
    volumes: 
      - ferdelance-server-data:/ferdelance/data
    networks:
      - www
      - ferdelance
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ferdelance.rule=Host(`ferdelance.${DOMAIN}`)"
      - "traefik.http.routers.ferdelance.entrypoints=web"
      - "traefik.http.services.ferdelance.loadbalancer.server.port=1456"
