version: '3.3'

networks:
  ferdelance:
  www:
    external: true

volumes:
  ferdelance-server-data:
  ferdelance-db-data:


services:

  # Python packages repository
  repository:
    image: idsia.ferdelance.repository
    container_name: repository
    networks:
      - ferdelance
      - www
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.repo.entrypoints=web"
      - "traefik.http.routers.repo.rule=Host(`fdl-repo.${DOMAIN}`)"
      - "traefik.http.services.repo.loadbalancer.server.port=8080"

  # Ferdelance internal database
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=${DATABASE_USER?Missing DATABASE_USER for database}
      - POSTGRES_PASSWORD=${DATABASE_PASS?Missing DATABASE_PASS for database}
      - POSTGRES_DB=${DATABASE_SCHEMA?Missing DATABASE_SCHEMA for database}
    volumes:
      - ferdelance-db-data:/var/lib/postgresql/data
    networks:
      - ferdelance

  # Task Broker - Where server communicates the tasks to the worker
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - ferdelance
    command: rabbitmq-server

  # Result Storage - Where worker stores results
  redis:
    image: redis
    container_name: redis
    networks:
      - ferdelance
    command: redis-server

  # Ferdelance Worker - Server internal worker
  worker:
    image: idsia.ferdelance.server
    container_name: worker
    environment:
      - WORKER_SERVER_HOST=server
      - CELERY_BROKER_URL=pyamqp://rabbitmq/
      - CELERY_BACKEND_URL=redis://redis/
      - CELERY_QUEUE=${CELERY_QUEUE}
    networks:
      - ferdelance
    command: --target worker
    depends_on:
      - redis
      - rabbitmq

  # Ferdelance server
  server:
    image: idsia.ferdelance.server
    container_name: server
    environment:
      - DB_HOST=database
      - DB_USER=${DATABASE_USER?Missing DATABASE_USER for server}
      - DB_PASS=${DATABASE_PASS?Missing DATABASE_PASS for server}
      - DB_SCHEMA=${DATABASE_SCHEMA?Missing DATABASE_SCHEMA for server}
      - SERVER_MAIN_PASSWORD=${SERVER_MAIN_PASSWORD?Missing SERVER_MAIN_PASSWORD for server}
      - CELERY_BROKER_URL=pyamqp://rabbitmq/
      - CELERY_BACKEND_URL=redis://redis/
    volumes:
      - ./storage:/ferdelance/storage
    networks:
      - www
      - ferdelance
    command: --target server
    depends_on:
      - database
      - worker
      - repository
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ferdelance.entrypoints=web"
      - "traefik.http.routers.ferdelance.rule=Host(`ferdelance.${DOMAIN}`)"
      - "traefik.http.services.ferdelance.loadbalancer.server.port=1456"
