version: '3.3'


services:

  # Python packages repository
  repository:
    container_name: repository
    image: idsia.ferdelance.repository
    build:
      context: .
      dockerfile: docker/Dockerfile.pypirepo

  # Ferdelance framework
  ferdelance:
    container_name: ferdelance
    image: idsia.ferdelance
    build:
      context: .
      dockerfile: docker/Dockerfile
