version: '3.3'

networks:
  ferdelance:
  www:
    external: true

volumes:
  ferdelance-server-data:
  ferdelance-db-data:

services:

  # FerDeLance internal database

  database:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_SCHEMA}
    ports:
      - 5432:5432
    volumes:
      - ferdelance-db-data:/var/lib/postgresql/data
    networks:
      - ferdelance

  # Tark Broker - Where server communicates the tasks to the worker

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq-broker
    networks:
      - ferdelance
    command: rabbitmq-server

  # Result Storage - Where worker stores results

  redis:
    image: redis
    container_name: redis-backend
    networks:
      - ferdelance
    command: redis-server

  # Worker - The actual worker

  worker: 
    image: idsia.ferdelance.server
    container_name: celery-worker
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}/${DATABASE_SCHEMA}
      - SERVER_URL=http://server
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
    volumes: 
      - ferdelance-server-data:/ferdelance/data
    networks:
      - ferdelance
    command: --target worker
    depends_on:
      - redis
      - rabbitmq
  
  # Monitor - Where worker status can be monitored

  flower:
    image: idsia.ferdelance.server
    container_name: celery-flower
    networks:
      - www
      - ferdelance
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
    command: --target flower
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.entrypoints=web"
      - "traefik.http.routers.flower.rule=Host(`flower-ferdelance.${DOMAIN}`)"
      - "traefik.http.services.flower.loadbalancer.server.port=5555"
    depends_on:
      - worker    
  
  # FerDeLance server
  
  server: 
    image: idsia.ferdelance.server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}/${DATABASE_SCHEMA}
      - SERVER_MAIN_PASSWORD=${SERVER_MAIN_PASSWORD}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}
    volumes: 
      - ferdelance-server-data:/ferdelance/storage
    networks:
      - www
      - ferdelance
    command: --target server
    depends_on:
      - database
      - worker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ferdelance.entrypoints=web"
      - "traefik.http.routers.ferdelance.rule=Host(`ferdelance.${DOMAIN}`)"
      - "traefik.http.services.ferdelance.loadbalancer.server.port=1456"
