version: '3.3'

networks:
  ferdelance:
  www:
    external: true

volumes:
  ferdelance-server-data:
  ferdelance-db-data:


services:

  # Python packages repository
  repository:
    image: idsia.ferdelance.repository
    container_name: repository
    build:
      context: .
      dockerfile: docker/Dockerfile.pypirepo
    networks:
      - ferdelance
    networks:
      - www
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ferdelance.entrypoints=web"
      - "traefik.http.routers.ferdelance.rule=Host(`ferdelancerepo.${DOMAIN}`)"
      - "traefik.http.services.ferdelance.loadbalancer.server.port=8080"

  # Ferdelance internal database
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_SCHEMA}
    ports:
      - 5432:5432
    volumes:
      - ferdelance-db-data:/var/lib/postgresql/data
    networks:
      - ferdelance

  # Task Broker - Where server communicates the tasks to the worker
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - ferdelance
    command: rabbitmq-server

  # Result Storage - Where worker stores results
  redis:
    image: redis
    container_name: redis
    networks:
      - ferdelance
    command: redis-server

  # Ferdelane Worker - Server internal worker
  worker:
    image: idsia.ferdelance.server
    container_name: worker
    environment:
      - DB_HOST=${DATABASE_HOST}
      - DB_USER=${DATABASE_USER}
      - DB_PASS=${DATABASE_PASS}
      - DB_SCHEMA=${DATABASE_SCHEMA}
      - CELERY_BROKER_URL=pyamqp://rabbitmq/
      - CELERY_BACKEND_URL=redis://redis/
    volumes:
      - ferdelance-server-data:/ferdelance/data
    networks:
      - ferdelance
    command: --target worker
    depends_on:
      - redis
      - rabbitmq

  # Ferdelance server
  server:
    image: idsia.ferdelance.server
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    environment:
      - DB_HOST=${DATABASE_HOST}
      - DB_USER=${DATABASE_USER}
      - DB_PASS=${DATABASE_PASS}
      - DB_SCHEMA=${DATABASE_SCHEMA}
      - SERVER_MAIN_PASSWORD=${SERVER_MAIN_PASSWORD}
      - CELERY_BROKER_URL=pyamqp://rabbitmq/
      - CELERY_BACKEND_URL=redis://redis/
    container_name: server
    volumes:
      - ./storage:/ferdelance/storage
    networks:
      - www
      - ferdelance
    command: --target server
    depends_on:
      - database
      - worker
      - repository
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ferdelance.entrypoints=web"
      - "traefik.http.routers.ferdelance.rule=Host(`ferdelance.${DOMAIN}`)"
      - "traefik.http.services.ferdelance.loadbalancer.server.port=1456"
