server: http://localhost:8080/
heartbeat: 2.0
workdir: ./workdir
private_key_location: ./private_key.pem

datasources:
  - name: source1
    type: csv
    path: data/file1.csv
    kind: file
    token: 6ec7f883cb714716f95d70841826609738f7993dea1664b98c34e5813e20d7d4

  - name: source2
    type: tsv
    path: data/file2.tsv
    kind: file
    token: 6ec7f883cb714716f95d70841826609738f7993dea1664b98c34e5813e20d7d4

  - name: iris
    type: csv
    path: data/iris.csv
    kind: file
    token: example_123

  # - name: database1
  #   type: sqlite
  #   conn: sqlite.db
  #   kind: db
  #   token: <...>

  # - name: database2
  #   type: postgres
  #   conn: postgresql://user:password@localhost:5432
  #   kind: db
  #   token: <...>
