server:
  password: ""

  protocol: http
  interface: localhost # use 0.0.0.0 in prod, 127.0.0.1 in dev
  port: 1456
  # this will produce http://localhost:1456/

  storage: ./storage # workdir for api

  tokens:
    client:
      expiration: 90 day
    user:
      expiration: 30 days
    project:
      default: ""

database:
  user: ""
  password: ""
  schema: ferdelance

  # in memory db (True)
  memory: False

  # sqlite (local/dev)
  dialect: sqlite
  host: ./sqlite

  # postgres (prod)
  # dialect: postresql
  # port: 5432
  # host: ""

client:
  heartbeat: 2.0
  workdir: ./workdir
  private_key_location: ./private_key.pem

datasources:
  # - name: source1
  #   type: csv
  #   path: data/file1.csv
  #   kind: file
  #   token: 58981bcbab77ef4b8e01207134c38873e0936a9ab88cd76b243a2e2c85390b94

  # - name: source2
  #   type: tsv
  #   path: data/file2.tsv
  #   kind: file
  #   token: 
  #   - 58981bcbab77ef4b8e01207134c38873e0936a9ab88cd76b243a2e2c85390b94

  - name: iris
    type: csv
    path: data/iris.csv
    kind: file
    token: 
    - 58981bcbab77ef4b8e01207134c38873e0936a9ab88cd76b243a2e2c85390b94

  # - name: database1
  #   type: sqlite
  #   conn: sqlite.db
  #   kind: db
  #   token: <...>

  # - name: database2
  #   type: postgres
  #   conn: postgresql://user:password@localhost:5432
  #   kind: db
  #   token: <...>
