server: http://localhost:8080
workdir: ./workdir
heartbeat: 10.0
datasources:
- name: source1
  type: csv
  path: data/file1.csv
  kind: file
- name: source2
  type: tsv
  path: data/file2.tsv
  kind: file
- name: source3
  type: tsv
  path: data/file3.tsv
  kind: file
- name: iris
  type: csv
  path: data/iris.csv
  kind: file